---
- name: Setup operating system
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "setup-{{ ansible_os_family }}.yml"
      skip: 'True'

- name: Install package
  package:
    name: "{{ item }}"
  with_items: "{{ package_list }}"
  when: package_list is defined

- name: Unarchive a awscli2
  unarchive:
    src: "{{ awscli_url }}"
    dest: /opt
    remote_src: yes

- name: Install awscli2
  command: /opt/aws/install -b "{{ bin_dir }}" --update

