# Package name.
docker_package_name: 'docker-ce'
docker_package_version: '18.09.9-3.el7'

# Docker Compose options.
docker_compose_version: "1.24.1"
docker_compose_url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64'
docker_compose_path: /usr/bin/docker-compose

# Set apt repository for Debian family.
apt_key_url: 'https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg'
apt_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower}} bionic stable"

# Set yum repository for RedHat family.
yum_repository: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/{{ docker_package_name }}.repo"

