---
# tasks file for bases

- name: Setup operating system
  include_tasks: "{{ item }}"
  with_first_found:
    - files: "setup-{{ ansible_os_family }}.yml"
      skip: 'True'

- name: Gather OS family variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install package
  package:
    name: "{{ item }}"
  with_items: "{{ package_list }}"
  when: package_list is defined

- name: Remove root history.
  ansible.builtin.shell: |
    rm /root/.bash_history
    ln -s /dev/null /root/.bash_history
    exit 0
  args:
    executable: /bin/bash
