- name: Install ad_auth required tools
  package:
    name:
      - krb5-workstation
      - realmd
      - sssd
      - samba-common-tools
      - adcli
      - oddjob
      - oddjob-mkhomedir
    state: present

- name: Check if machine is bound
  shell: "{{ realm_path }} list | grep {{ adauth_realm.split('.')[-2:] | join('.') }}"
  register: realm_bound
  changed_when: false
  ignore_errors: true

- name: Join system to AD
  shell: "echo {{ adauth_password }} | {{ realm_path }} join --user={{ adauth_username }} --client-software=sssd {{ adauth_realm }}"
  when: realm_bound.rc != 0

- name: modifie sssd conf
  lineinfile:
    path: '{{ sssd_conf_path }}'
    regexp: '^{{ conf.key }}'
    line: '{{ conf.key }}={{ conf.value }}'
    backrefs: yes
  with_dict: "{{ sssd_conf_vars }}"
  loop_control:
    loop_var: conf
  when: realm_bound.rc != 0
  notify:
    - restart sssd

