---

- name: "Adding user '{{ item.username }}' to the system"
  user:
    name: "{{ item.username }}"
    uid: "{{ item.uid | default(omit) }}"
    home: "{{ item.home | default(users_home ~ '/' ~ item.username ) }}"
    comment: "{{ item.name | default(omit) }}"
    system: "{{ item.system | default(omit) }}"
    generate_ssh_key: "{{ item.ssh_key_generate | default(omit) }}"
    group: "{{
            omit if item.group is defined and item.group == item.username
            else (item.group if item.group is defined else (users_group if users_group else omit))
            }}"
    groups: "{{ item.groups|join(',') if item.groups is defined else users_groups|join(',') }}"
    append: "{{ item.append | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    ssh_key_file: ".ssh/id_{{ item.ssh_key_type | default(users_ssh_key_type) }}"
    ssh_key_passphrase: "{{ item.ssh_key_password | default(omit) }}"
    ssh_key_bits: "{{ item.ssh_key_bits | default(users_ssh_key_bits) }}"
    createhome: "{{ item.home_create | default(users_home_create) }}"
    shell: "{{ item.shell | default(users_shell | default(omit)) }}"
    update_password: "{{ item.update_password | default(omit) }}"

- name: Configuring user's home
  import_tasks: manage_user_home.yml
  when: item.home_create | default(users_home_create)
