---

- name: Adding primary group
  group:
    name: "{{ users_group }}"
    state: present
  when: users_group is defined and users_group

- name: Adding secondary groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ users_groups | default([]) }}"

- name: Configure users
  include_tasks: manage_user.yml
  with_items: "{{ users }}"

- name: Ensuring that wheel is able to use sudo without password
  lineinfile:
    path: /etc/sudoers
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Removing users
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: "{{ users_remove }}"
