---
- name: Load a variable file based on the OS type.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Setting sysctl.conf
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    ignoreerrors: yes
  with_dict: "{{ sysctl_conf }}"
  when: sysctl_conf is defined

- name: Install transparent hugepage service
  template:
    src: disable_thg.service.j2
    dest: "{{ daemon_folder }}/disable_thg.service"
    owner: root
    group: root
    mode: '0644'
  when: (ansible_os_family == "RedHat") and (disable_thg is defined) and (disable_thg|bool == True)
  register: result

- name: Start service disable_thg
  systemd:
    name: disable_thg
    state: started
    enabled: yes
    daemon_reload: yes
  when: (ansible_os_family == "RedHat") and (result is succeeded) and (result.skipped is not defined )

- name: Setting ulimit
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  with_items: "{{ limits_conf }}"
  when: limits_conf is defined
