- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present

- name: Add Docker apt key.
  apt_key:
    url: "{{ apt_key_url }}"
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ apt_repository }}"
    state: present
    update_cache: true

