- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-common
      - docker-engine
    state: absent

- name: Add Docker repository.
  get_url:
    url: "{{ yum_repository }}"
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Set docker package
  set_fact:
    docker_package_name: "{{ yum_docker_package_name }}"
  when: yum_docker_package_name is defined and yum_docker_package_name

