- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
      - docker.io
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present

- name: Add Docker apt key.
  apt_key:
    url: "{{ apt_key_url }}"
    keyring: /etc/apt/trusted.gpg.d/docker-apt-key.gpg
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ apt_repository }}"
    state: present
    update_cache: true

- name: Set docker package
  set_fact:
    docker_package_name: "{{ apk_docker_package_name }}"
  when: apk_docker_package_name is defined and apk_docker_package_name
