- hosts: all
  gather_facts: true
  become: yes
  vars:
    git_list: []
  roles:
    - bases
    - git
    - docker
    - hostname
    - known_hosts
    - timezone
    - performance
    - users
    - ssh
    - awscli
