galaxy_info:
  author: chiehting
  description: Install Docker and Docker Compose.
  license: license (BSD, MIT)
  min_ansible_version: 2.4
  platforms:
    - name: Ubuntu
      versions:
      - 18.04
    - name: Centos
      versions:
      - 7
  galaxy_tags:
    - docker
    - compose
    - container

